restricted metadata changes
PureStorage-OpenConnect/Pure-PowerVC-Cinder pull request #5
Opened 2021-04-20 12:18 UTC by Karthikmvdp

2021-04-20 12:41 UTC, chhagarw commented
@Karthikmvdp can u also add the changes to have volume metadata,  model_update to have vdisk_uid assigned as volume_wwn.

 model_update = super(PowerPureFCDriver, self).\
            create_volume(vol_copy)
        return self._model_update(model_update, vol_copy)

    def _model_update(self, model_update, volume):
        """add volume wwn to the metadata of the new volume"""
        if not model_update:
            model_update = {}
        meta = self.db.volume_metadata_get(
            context.get_admin_context(), volume['id'])
        model_update['metadata'] = meta if meta else dict()
        attrs = self.get_volume_info(volume)
        model_update['metadata']['volume_wwn'] = attrs['vdisk_UID']
        return model_update

2021-04-20 12:53 UTC, sdodsley requested changes

2021-04-20 12:53 UTC, sdodsley commented on pure_powervc.py
> +                                    err=six.text_type(ex))))
`six` is no longer to be used in Cinder code - please change.

2021-04-20 12:53 UTC, sdodsley commented on pure_powervc.py
> +import six
`six` not approved in latest Cinder code base

2021-04-20 14:47 UTC, chhagarw reviewed
@sdodsley currently we are using get_volume_info, which uses  
pure_volumes = current_array.list_volumes()
and traverse to get the volume details, does purestorage has an interface to get the volume info of a single volume

2021-04-21 18:53 UTC, sdodsley commented
Yes - I sent details over - you can use `get_volume(<volume_name)`

2021-04-21 19:00 UTC, sdodsley requested changes

2021-04-21 19:00 UTC, sdodsley commented on pure_powervc.py
> +            args[0]._validate_type(args[vol_arg])
I don't see a function definition for `_validate_type` so this will cause the driver to crash

2021-04-27 16:38 UTC, sdodsley commented
@Karthikmvdp are you sure this is correct?
I just used this latest version in my PowerVC 2.0.0 system and it crashed with the following error
```
2021-04-27 12:37:05.518 1764570 ERROR cinder Traceback (most recent call last):
2021-04-27 12:37:05.518 1764570 ERROR cinder   File "/usr/bin/cinder-volume", line 10, in <module>
2021-04-27 12:37:05.518 1764570 ERROR cinder     sys.exit(main())
2021-04-27 12:37:05.518 1764570 ERROR cinder   File "/usr/lib/python3.6/site-packages/cinder/cmd/volume.py", line 232, in main
2021-04-27 12:37:05.518 1764570 ERROR cinder     _launch_services_pvc()
2021-04-27 12:37:05.518 1764570 ERROR cinder   File "/usr/lib/python3.6/site-packages/cinder/cmd/volume.py", line 194, in _launch_services_pvc
2021-04-27 12:37:05.518 1764570 ERROR cinder     _launch_service_pvc(launcher, CONF.backend_host)
2021-04-27 12:37:05.518 1764570 ERROR cinder   File "/usr/lib/python3.6/site-packages/cinder/cmd/volume.py", line 128, in _launch_service_pvc
2021-04-27 12:37:05.518 1764570 ERROR cinder     cluster=CONF.cluster)
2021-04-27 12:37:05.518 1764570 ERROR cinder   File "/usr/lib/python3.6/site-packages/cinder/service.py", line 406, in create
2021-04-27 12:37:05.518 1764570 ERROR cinder     cluster=cluster, **kwargs)
2021-04-27 12:37:05.518 1764570 ERROR cinder   File "/usr/lib/python3.6/site-packages/cinder/service.py", line 156, in __init__
2021-04-27 12:37:05.518 1764570 ERROR cinder     *args, **kwargs)
2021-04-27 12:37:05.518 1764570 ERROR cinder   File "/usr/lib/python3.6/site-packages/powervc_cinder/volume/manager.py", line 494, in __init__
2021-04-27 12:37:05.518 1764570 ERROR cinder     service_name=service_name, *args, **kwargs)
2021-04-27 12:37:05.518 1764570 ERROR cinder   File "/usr/lib/python3.6/site-packages/cinder/volume/manager.py", line 275, in __init__
2021-04-27 12:37:05.518 1764570 ERROR cinder     active_backend_id=curr_active_backend_id)
2021-04-27 12:37:05.518 1764570 ERROR cinder   File "/usr/lib/python3.6/site-packages/oslo_utils/importutils.py", line 44, in import_object
2021-04-27 12:37:05.518 1764570 ERROR cinder     return import_class(import_str)(*args, **kwargs)
2021-04-27 12:37:05.518 1764570 ERROR cinder   File "/usr/lib/python3.6/site-packages/oslo_utils/importutils.py", line 30, in import_class
2021-04-27 12:37:05.518 1764570 ERROR cinder     __import__(mod_str)
2021-04-27 12:37:05.518 1764570 ERROR cinder   File "/usr/lib/python3.6/site-packages/cinder/volume/drivers/pure_powervc.py", line 46, in <module>
2021-04-27 12:37:05.518 1764570 ERROR cinder     from powervc_cinder.volume.discovery_driver \
2021-04-27 12:37:05.518 1764570 ERROR cinder ImportError: cannot import name 'RESTRICTED_METADATA_VDISK_pg83NAA_KEY'

```

2021-04-27 16:55 UTC, Karthikmvdp commented
@chhagarw @shyamav @sdodsley I have updated my change set.

2021-04-27 17:03 UTC, sdodsley commented
@Karthikmvdp do you have an updated `discovery_driver.py` I can test this with, or will upgrading to 2.0.1 resolve this crash?

2021-04-27 17:28 UTC, Karthikmvdp commented
@sdodsley we have changes in discovery driver, you need to update the discovery_driver.py to resolve the crash.

2021-04-27 17:29 UTC, sdodsley commented
@Karthikmvdp can you send me the updated version so I can test out the fixes?

2021-04-27 17:39 UTC, Karthikmvdp commented
@sdodsley sent changes via mail.

2021-04-27 18:08 UTC, sdodsley commented
OK - I can't test LKU in my environment, but it runs fine with those updated files.

2021-04-27 18:08 UTC, merged